
version: '3.9'
services:
  mysql-auth:
    image: mysql:8
    container_name: mysql-auth
    environment:
      MYSQL_DATABASE: authdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - auth-data:/var/lib/mysql

  mysql-student:
    image: mysql:8
    container_name: mysql-student
    environment:
      MYSQL_DATABASE: studentdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - student-data:/var/lib/mysql

  mysql-grade:
    image: mysql:8
    container_name: mysql-grade
    environment:
      MYSQL_DATABASE: gradedb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - grade-data:/var/lib/mysql

  mysql-course:
    image: mysql:8
    container_name: mysql-course
    environment:
      MYSQL_DATABASE: coursedb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    volumes:
      - course-data:/var/lib/mysql

  mysql-professor:
    image: mysql:8
    container_name: mysql-professor
    environment:
      MYSQL_DATABASE: professordb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3311:3306"
    volumes:
      - professor-data:/var/lib/mysql

volumes:
  auth-data:
  student-data:
  grade-data:
  course-data:
  professor-data:
